global:
  amqp: amqp://guest:guest@amqp:5672/                 # AMQP server URL
  log-level: info                                     # Log filtering level (debug, info, warn, error)
  log-color: true                                     # Enable colors in logs
  log-datetime: true                                  # Enable datetime prefix in logs
  log-dir: logs                                       # The directory in which logs are stored
  instance-id: Koinos                                 # ID that uniquely identifies the instance
  fork-algorithm: pob                                 # Fork resolution algorithm (fifo, pob, block-time)
  blacklist:                                          # RPC targets to blacklist, can be an entire microservice (i.e. chain), or specific API calls
    - block_store.add_block
    - chain.propose_block
  # jobs: 32                                          # Number of jobs to run
  # reset: true                                       # DANGEROUS: Resets the entire node. To reset a single microservice, set this in the microservice config
  # whitelist:                                        # RPC targets to whitelist
  # - RPC

# account-history:
  # address-whitelist:                                # Addresses to track
  # - ADDRESS

block_producer:
  algorithm: pob                                      # Block production algorithm
  # producer:                                         # Address at which which blocks are produced
  # private-key-file: private.key                     # File containing the private key with which blocks are produced
  # max-inclusion-attempts: 2000                      # Maximum number of transactions attempted to be included in a block
  # resources-lower-bound: 75                         # Percent resource utilization lower bound target to consider adequate for submission
  # resources-upper-bound: 90                         # Percent resource utilization upper bound to consider block "full"
  # gossip-production: false                          # Disable requiring p2p gossip before block production, this is not recommended
  # approve-proposals:                                # Proposals to approve when producing blocks
  # - PROPOSAL_ID

# block_store:

# chain:
  # disable-pending-transaction-limit: false          # Disable the pending transaction limit
  # pending-transaction-limit: 10                     # Per address pending transaction limit
  # read-compute-bandwidth-limit: 10000000            # Compute bandwidth limit when reading contracts via the API
  # system-call-buffer-size: 64000                    # Buffer call in bytes used for the invoke_system_call API

# contract-meta-store:

grpc:
  endpoint: 0.0.0.0:50051
  # gateway-timeout: 3                                # Timeout in seconds to enqueue a request
  # mq-timeout: 5                                     # Timeout in seconds to receive MQ response

jsonrpc:
  listen: /tcp/8080                                   # Multiaddress on which to listen
  # endpoint: /                                       # HTTP endpoint to listen on
  # gateway-timeout: 3                                # Timeout in seconds to enqueue a request
  # mq-timeout: 5                                     # Timeout in seconds to receive MQ response

# mempool:
  # transaction-expiration: 120                       # Number of seconds a transaction should expire in

p2p:
  listen: /ip4/0.0.0.0/tcp/8888                       # Multiaddress on which to listen
  peer:                                               # Peer seed nodes
    - /dns4/seed.koinosblocks.com/tcp/8888/p2p/QmUNURuZxSu5wLnmBNJdwGtwjLmV5JxGhu4uNSAS8ZNcze
    - /dns4/seed.koinosfoundation.org/tcp/8888/p2p/QmUCTQEA28NArt3oCZaVc1nbntMbaey24atAdogZ8kfaKg
    - /dns4/east.burnkoin.com/tcp/8888/p2p/QmYAC9nxqgVt2p8NvmxNFsoMpQS7c4zEBmsZndEBTRHNu4
  # checkpoint:                                       # Checkpoints required in synced chain
  #  - BLOCK_HEIGHT:BLOCK_ID
  # disable-gossip: true                              # Disables gossip, this is not recommended
  # force-gossip: true                                # Forces gossip to always be enabled, this is not recommended
  # seed: MY_SECRET_SEED_PHRASE                       # Seed string to generate a peer ID, this should only be used when configuring the node as a seed node

# transaction-store:
