global:
  amqp: amqp://guest:guest@amqp:5672/
  log-level: info
  instance-id: Koinos

block_producer:
  algorithm: pob
  pob-contract-id: 159myq5YUhhoVWu3wsHKHiJYKPKGUrGiyv
  vhp-contract-id: 1AdzuXSpC6K9qtXdCBgD5NUpDNwHjMgrc9
  # producer:

chain:
  fork-algorithm: pob

jsonrpc:
  listen: /tcp/8080

p2p:
  listen: /ip4/0.0.0.0/tcp/8888
  peer:
    - /dns4/seed.koinos.io/tcp/8888/p2p/Qmd2bkf65yCKVZb2PG3FiRQWzrYgKf47zGBFuoU5qdebEY
