global:
  amqp: amqp://guest:guest@amqp:5672/
  log-level: info
  instance-id: Koinos

block_producer:
  algorithm: pob
  pob-contract-id: 198RuEouhgiiaQm7uGfaXS6jqZr6g6nyoR
  vhp-contract-id: 1JZqj7dDrK5LzvdJgufYBJNUFo88xBoWC8
  # producer:

chain:
  fork-algorithm: pob

jsonrpc:
  listen: /tcp/8080

p2p:
  listen: /ip4/0.0.0.0/tcp/8888
  peer:
    - /dns4/harbinger-seed.koinos.io/tcp/8888/p2p/QmcGiTpSm6YrmYo3rWoqrCPez2aJY4VdraBQsGsZKwFRuG
